begin;
do $$
declare org uuid; actor uuid; sid uuid; sid2 uuid; v bigint; pid uuid := gen_random_uuid(); child uuid := gen_random_uuid(); p public.script_pages%rowtype; n integer;
begin
  select organization_id,user_id into org,actor from public.memberships where role='owner' and status='active' limit 1;
  if actor is null then raise exception 'Missing fixture owner'; end if;
  perform set_config('request.jwt.claim.sub',actor::text,true);
  set local role authenticated;
  sid := public.create_board_script(org,'اختبار بورد معزول','draft','نص محفوظ لا يتم مسحه عند نقل الكارت','educational','مرجع محفوظ',60,'idea');
  select edit_version into v from public.scripts where id=sid;
  v := public.move_script_card(sid,v,'idea');
  if not exists(select 1 from public.scripts where id=sid and draft_stage='idea' and spoken_script='نص محفوظ لا يتم مسحه عند نقل الكارت') then raise exception 'Text lost'; end if;
  begin perform public.move_script_card(sid,v-1,'draft'); raise exception 'Stale move accepted'; exception when others then if sqlerrm not like '%جلسة أخرى%' then raise; end if; end;
  begin perform public.move_script_card(sid,v,'published'); raise exception 'False publication accepted'; exception when others then if sqlerrm not like '%المهام%' then raise; end if; end;
  p := public.save_script_page(sid,pid,null,'الصفحة الرئيسية','نص الصفحة',0);
  p := public.save_script_page(sid,pid,null,'الصفحة الرئيسية','نص الصفحة',0);
  p := public.save_script_page(sid,child,pid,'صفحة داخلية','النص الداخلي',0);
  if (select count(*) from public.script_pages where script_id=sid)<>2 then raise exception 'Duplicate page'; end if;
  p := public.save_script_page(sid,pid,null,'الصفحة الرئيسية','نص محدث',1);
  begin perform public.save_script_page(sid,pid,null,'الصفحة الرئيسية','قديم',1); raise exception 'Stale page accepted'; exception when others then if sqlerrm not like '%تغيّرت%' then raise; end if; end;
  begin perform public.save_script_page(sid,pid,child,'حلقة','نص',2); raise exception 'Cycle accepted'; exception when others then if sqlerrm not like '%مرجع%' then raise; end if; end;
  sid2 := public.create_board_script(org,'اختبار فكرة فارغة','idea','','educational','',60,'idea');
  select edit_version into n from public.scripts where id=sid2;
  begin perform public.move_script_card(sid2,n,'ready_to_record'); raise exception 'Empty ready accepted'; exception when others then if sqlerrm not like '%اكتب نص%' then raise; end if; end;
  begin perform public.save_script_page(sid2,gen_random_uuid(),pid,'أب من سكريبت آخر','نص',0); raise exception 'Cross-script parent accepted'; exception when others then if sqlerrm not like '%الأم%' then raise; end if; end;
  begin delete from public.script_pages where id=pid; raise exception 'Direct delete accepted'; exception when insufficient_privilege then null; end;
  perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
  if exists(select 1 from public.script_pages where script_id=sid) then raise exception 'Private page leaked'; end if;
  begin perform public.move_script_card(sid,v,'draft'); raise exception 'Other writer accepted'; exception when others then if sqlerrm not like '%متاح%' then raise; end if; end;
  begin perform public.save_script_page(sid,pid,null,'سرقة','نص',2); raise exception 'Other page writer accepted'; exception when others then if sqlerrm not like '%صلاحية%' then raise; end if; end;
  reset role;
  perform set_config('request.jwt.claim.sub',actor::text,true);
  update public.memberships set role='viewer' where organization_id=org and user_id=actor;
  set local role authenticated;
  begin perform public.move_script_card(sid,v,'draft'); raise exception 'Viewer move accepted'; exception when others then if sqlerrm not like '%متاح%' then raise; end if; end;
  begin perform public.save_script_page(sid,pid,null,'تعديل viewer','نص',2); raise exception 'Viewer page accepted'; exception when others then if sqlerrm not like '%صلاحية%' then raise; end if; end;
  reset role;
end; $$;
select 'PASS board create/move, no text loss, stale denial, nested page retry/CAS, cycle/cross-script denial, RLS, no direct deletes, unrelated/viewer denial; all changes rolled back' result;
rollback;
